# https://docs.docker.com/compose/compose-file
version: '3.8'  # @ Docker Engine 19.03.0+

x-logopts: # https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields 
    &common-logopts # https://docs.docker.com/compose/compose-file/compose-file-v3/#logging 
    options:
        max-size: '12m'
        max-file: '5'
    driver: json-file

volumes:  
    cache:

networks:
    web:

configs: 
    # To update source(s) sans stack cycling (docker stack ... rm/deploy), 
    # change the modified-source name(s) here and at their service(s).
    sites_list_csv:
        file: ${PATH_HOST_ROOT}/assets/${APP_SITES_LIST_CSV}
    sites_list_json:
        file: ${PATH_HOST_ROOT}/cache/${APP_SITES_LIST_JSON}

services:
    cli: 
        image: ${HUB}/${PRJ}.cli-${ARCH}:${VER_APP}
        volumes:
            #- cache:/app/cache
            - cache:/tmp/${PRJ}/cache
            # Bind mount @ host okay ONLY @ single-host (docker-desktop) swarm:
            - ${PATH_HOST_ROOT}/assets:/app/assets
        networks:
            - web
        # ports: # Unnecessary
        #     - 8080:80
        configs: 
            - sites_list_csv
            - sites_list_json
        env_file:
            - ${PATH_HOST_ROOT}/assets/.env/common.env
            - ${PATH_HOST_ROOT}/assets/.env/creds.${APP_SERVICE_HOST}.env
        command: ["/app/main", "upsertpostschron", "2"]
        deploy:
            replicas: 1
            restart_policy:
                condition: any
        logging: *common-logopts